# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_auto_20160307_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='mainstudent',
        ),
    ]
