# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0003_remove_group_mainstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mainstudent',
            field=models.CharField(default='Unknow', max_length=30),
        ),
    ]
