# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0004_group_mainstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='mainstudent',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
