# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stud', '0005_auto_20160327_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groupsapi', to=settings.AUTH_USER_MODEL),
        ),
    ]
