# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0006_group_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
    ]
